spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/edu_manager
    username: edu_admin
    password: edu_password_dev
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # MongoDB & Redis Configuration
  data:
    mongodb:
      uri: mongodb://admin:mongodb_password_dev@localhost:27017/edu_manager_docs?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: redis_password_dev

  # Spring Modulith Event Configuration
  modulith:
    events:
      publication-strategy: jpa
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: edu-manager-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Server Configuration
server:
  port: 8081

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.edumanager: DEBUG
    org.springframework.modulith: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE